-- Insert Fortitude Portugal Special Situations II fund
INSERT INTO public.funds (
  id,
  name,
  description,
  detailed_description,
  manager_name,
  minimum_investment,
  expected_return_min,
  expected_return_max,
  currency,
  risk_level,
  lock_up_period_months,
  management_fee,
  performance_fee,
  subscription_fee,
  aum,
  inception_date,
  website,
  category,
  geographic_allocation,
  tags,
  team_members,
  faqs,
  gv_eligible,
  regulated_by,
  location,
  auditor,
  custodian,
  redemption_terms,
  eligibility_basis,
  hurdle_rate,
  is_verified,
  created_at,
  updated_at
) VALUES (
  'fortitude-special-situations-ii',
  'Fortitude Portugal Special Situations II – Fundo de Capital de Risco Fechado',
  'Private equity fund targeting 15-20% IRR through special situations investments in Iberia, with Golden Visa eligibility and CMVM regulation.',
  'Fortitude Special Situations II is a €150M CMVM-regulated private equity fund focused on special situations investments across Iberia. The fund employs a downside-focused investment strategy with 90% proprietary deal sourcing. Investments target 15-25% exposure per position with equity, debt, and hybrid instruments. The experienced team, led by ex-Goldman Sachs and BTG Pactual partners, leverages differentiated sourcing capabilities and a robust advisory board including Paula Amorim, José María Pacheco, and Filipe de Botton. The fund features a full catch-up carry structure, 7% IRR hurdle rate, and comprehensive portfolio management with secondments and operational value creation. Investment period is 4 years with an 8-year term plus up to 2-year extension options.',
  'Fortitude Capital',
  100000,
  15,
  20,
  'EUR',
  'High-risk',
  48,
  2.0,
  20,
  5.0,
  150,
  '2025-01-01',
  null,
  'Private Equity',
  '[{"region": "Portugal", "percentage": 60}, {"region": "Spain", "percentage": 40}]'::jsonb,
  ARRAY['Private Equity', 'Golden Visa Eligible', 'Regulated', 'Special Situations', 'Closed Ended', '€100k-250k', 'High-risk', '> 5% annual yield', '5-10 year lock-up', '1-1.5% management fee'],
  '[
    {"name": "António Esteves", "position": "CEO & Partner", "bio": "Ex-Goldman Sachs Partner and ex-Merrill Lynch MD with 30+ years experience"},
    {"name": "Mário Vigário", "position": "CIO & Partner", "bio": "Founding Partner & CIO at Atrium, ex-Santander with 30+ years experience"},
    {"name": "Sofia Martins", "position": "COO & Partner", "bio": "COO at Atrium, ex-Deutsche Bank with 30+ years experience"},
    {"name": "Alexandre Camara", "position": "Partner", "bio": "Senior Partner & Executive Board Member at BTG Pactual with 25+ years experience"},
    {"name": "Edwyn Neves", "position": "Partner", "bio": "Partner at BTG Pactual, ex-Credit Suisse and Advent with 20+ years experience"}
  ]'::jsonb,
  '[
    {"question": "Is this fund Golden Visa eligible?", "answer": "Yes, Fortitude Special Situations II is explicitly Golden Visa eligible for Portugal''s residency program."},
    {"question": "What is the minimum investment?", "answer": "The minimum investment is €100,000."},
    {"question": "What is the target return?", "answer": "The fund targets a gross IRR of 15-20% with a 7% hurdle rate before performance fees apply."},
    {"question": "What sectors does the fund invest in?", "answer": "The fund is sector-agnostic and invests across special situations in Iberia, including agriculture, healthcare, hospitality, consumer goods, and infrastructure."},
    {"question": "What is the fund size and term?", "answer": "Target size is €150 million with an 8-year term, extendable up to 10 years (1+1 year extensions)."}
  ]'::jsonb,
  true,
  'CMVM',
  'Portugal',
  'Deloitte',
  'Banco Invest',
  '{"frequency": "End of Term", "redemptionOpen": false, "minimumHoldingPeriod": 48, "notes": "8-year term with up to 2 years extension (1+1). Post-investment period distributions to LPs."}'::jsonb,
  '{"portugalAllocation": 60, "maturityYears": 8, "managerAttestation": true}'::jsonb,
  7.0,
  false,
  now(),
  now()
);