name: Generate Redirects & Sitemap

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [main, develop]
    paths:
      - 'src/data/services/tags-service.ts'
      - 'src/data/services/categories-service.ts'
      - 'src/data/services/funds-service.ts'
      - 'scripts/ssg/generate-redirects.ts'
      - 'src/services/**/*sitemap*.ts'

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate redirects
        run: npm run generate:redirects
      
      - name: Generate sitemap
        run: npm run generate:sitemap || node scripts/generate-production-sitemap.js
      
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet vercel.json public/sitemap.xml public/sitemap-index.xml public/robots.txt; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push if changed
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add vercel.json public/sitemap*.xml public/robots.txt
          git commit -m "chore: auto-generate redirects and sitemap [skip ci]"
          git push
